# Generated by Django 5.2.13 on 2026-04-22 10:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Igrisca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('povrsina', models.CharField(choices=[('pesek', 'Pesek'), ('trava', 'Trava'), ('trda', 'Trda podlaga')], default='trda', max_length=20)),
                ('aktivno', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oprema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('kolicina', models.PositiveIntegerField(default=1)),
                ('cena_ura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aktivno', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('uporabnik', 'Uporabnik'), ('trener', 'Trener'), ('administrator', 'Administrator')], default='uporabnik', max_length=20)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('ura_zacetek', models.TimeField()),
                ('ura_konec', models.TimeField()),
                ('status', models.CharField(choices=[('cakajoca', 'Čakajoča'), ('potrjena', 'Potrjena'), ('zavrnjena', 'Zavrnjena'), ('preklicana', 'Preklicana')], default='potrjena', max_length=20)),
                ('ustvarjena', models.DateTimeField(auto_now_add=True)),
                ('igrisca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervacije.igrisca')),
                ('oprema', models.ManyToManyField(blank=True, to='rezervacije.oprema')),
                ('trener', models.ForeignKey(blank=True, limit_choices_to={'role': 'trener'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treningi', to=settings.AUTH_USER_MODEL)),
                ('uporabnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervacije', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('igrisca', 'datum', 'ura_zacetek')},
            },
        ),
    ]
