# Generated by Django 5.2.13 on 2026-04-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacije', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='igrisca',
            name='cena_ura',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
