# Generated by Django 5.2.13 on 2026-05-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacije', '0002_igrisca_cena_ura'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cena_ura',
            field=models.DecimalField(decimal_places=2, default=45.0, max_digits=6),
        ),
    ]
